version: "3"
services:
  hs-nginx:
    image: monimage
    restart: always
    container_name: nginx-hidden_service
    ports:
      - 80:80
    volumes:
      - .\data\onion/:/var/lib/tor/hostname
      - .\data\htdocs:/var/www/html
